// <auto-generated />
using System;
using Booking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booking.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221003005523_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Booking.Reservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("guestName")
                        .HasColumnType("TEXT");

                    b.Property<int>("guestNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("roomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("roomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Booking.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("roomName")
                        .HasColumnType("TEXT");

                    b.Property<int>("roomType")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Booking.Reservation", b =>
                {
                    b.HasOne("Booking.Room", "room")
                        .WithMany()
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("room");
                });
#pragma warning restore 612, 618
        }
    }
}
