// <auto-generated />
using System;
using Booking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booking.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Booking.Reservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("guestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("guestNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("roomType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("roomid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("roomid");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Booking.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("roomType")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Booking.Reservation", b =>
                {
                    b.HasOne("Booking.Room", "room")
                        .WithMany()
                        .HasForeignKey("roomid");

                    b.Navigation("room");
                });
#pragma warning restore 612, 618
        }
    }
}
